const textAbilitiesRegex = {

    // card draw

    drawCard: /.*\bdraw a card(?:\.|\;)\b.*/i,
    drawCards: /.*draw (\d) cards(?:\.|\;).*/i,
    drawSecret: /.*draw a secret.*/i,
    drawCardDamagedCharacter: /.*draw a card for each damaged friendly character.*/i,
    drawWeapon: /.*draw a weapon.*/i,
    drawEachPlayers: /.*each players draws (\d) cards.*/i,
    drawCardUntilHand: /.*draw cards until you have as many in hand as your opponent.*/i,
    drawForEach: /.*draw a card for each.*/i,
    drawMinions: /.*draw (\d) minions.*/i,
    drawTwoCards: /.*draw two cards.*/i,
    drawWeapons: /.*draw (\d) weapons.*/i,
    drawUntil: /.*both players draw until they have (\d) cards.*/i,
    drawDivineMinion: /.*draw a divine shield minion.*/i,
    drawCardDurability: /.*draw cards equal to its durability.*/i,
    drawMurlocs: /.*draw (\d) murlocs.*/i,
    drawCardAndDeal: /.*draw a card and deal damage equal to its cost.*/i,
    drawAnExtraCard: /.*draw an extra card.*/i,
    drawOpponentCards: /.*your opponent draws (\d) cards.*/i,
    drawThreeOneCostMinions: /.*draw three 1-cost minions.*/i,
    drawTwoOneCostMinions: /.*draw two 1-cost minions.*/i,
    drawBDM: /.*draw a beast, dragon and murlock.*/i,
    drawOneAndDiscard: /.*draw one and discard the others.*/i,
    drawDreamCard: /.*draw a dream card.*/i,
    drawCardUntilDragon: /.*draw cards until you draw one that isn't a dragon.*/i,
    
    // cast

    castRepeat: /.*if any die, cast this again.*/i,
    castSpellDeck: /.*cast a spell from your deck.*/i,
    castEI: /.*cast an elemental invocation.*/i,
    castEachSpellGameMinion: /.*cast each spell you cast on your minions this game on this one.*/i,
    castRandomSpell: /.*cast a random spell.*/i,
    castRandomSpellEach: /.*cast a random spell for each spell you've cast this game.*/i,
    castIfMoreAgain: /.*if your opponent has more minions, cast this again.*/i,
    discoverAndCast: /.*discover a spell and cast it with random targets.*/i,

    // copy

    copyCard: /.*copy a card from your opponent's deck and add it to your hand.*/i,
    copyCards: /.*copy (\d) cards (?:from|in) your opponent's deck and (?:put|add) them (?:into|to) your hand.*/i,
    copyGuess: /.*guess which one started.*to get copy a copy of it.*/i,
    copyChooseMinion: /.*choose a minion and become a copy of it.*/i,
    copyFriendlyStats: /.*copy a friendly minion's attack and health.*/i,
    copyAfterAttack: /.*after this minion attacks a hero, add a copy of it to your hand.*/i,
    copyAfterSomething: /.*then add a copy of it to your hand.*/i,
    copyRandomCardHand: /.*put a copy of a random card in your.*hand.*/i,
    copyRandomCardDeck: /.*put a copy of a random minion from.*battlefield.*/i,
    copyFrozenMinion: /.*is Frozen, add a copy of it to your hand.*/i,
    copySpell: /.*copy a spell in your opponent's deck.*/i,
    copyDiscoverSpell: /.*a copy of a spell in your deck.*/i,
    copyDiscoverMinion: /.*a copy of a minion in your deck.*/i,
    copyTheLowestMinion: /.*copy the lowest cost minion in your hand.*/i,

    // deal damage

    dealAllCharacters: /.*deal (\d) damage to all characters.*/i,
    dealAllOtherCharacters: /.*deal (\d) damage to all other characters.*/i,
    dealAllMinions: /.*deal (\d) damage to all minions.*/i,
    dealMinion: /.*deal (\d) damage to a minion.*/i,
    dealAllEnemyMinions: /.*deal (\d) damage to all enemy minions.*/i,
    dealRandomlyEnemyCharacters: /.*deal (\d) damage randomly.*enemy characters.*/i,
    dealDamages: /.*deal (\d) damage(?:\.|\;).*/i,
    dealAdjacentOnes: /.*(\d) damage to adjacent ones.*/i,
    dealUndamagedMinion: /.*deal (\d) damage to an undamaged minion.*/i,
    dealUndamagedCharacter: /.*deal (\d) damage to an undamaged character.*/i,
    dealEnemyHero: /.*deal (\d) damage to the enemy hero.*/i,
    dealCharacter: /.*deal (\d) damage to a character.*/i,
    dealNextToIt: /.*deal its damage to the minions next to it.*/i,
    dealYourHero: /.*deal (\d) damage to your hero(?:\.|\;).*/i,
    dealThatMuch: /.*deal that much damage to a random enemy minion.*/i,
    dealItsAllEnemyMinions: /.*deal its damage to all enemy minions.*/i,
    dealEnemyMinion: /.*deal (\d) damage to an enemy minion.*/i,
    dealRandomEnemyMinion: /.*deal (\d) damage to a random enemy minion.*/i,
    dealYourHeroEqualCost: /.*deal (\d) damage to your hero equal to its cost.*/i,
    dealTwoRandomEnemyMinions: /.*deal (\d) damage to two random enemy minions.*/i,
    dealAllEnemies: /.*deal (\d) damage to all enemies.*/i,
    dealToThem: /.*deal (\d) damage to them.*/i,
    dealNonMurloc: /.*deal (\d) damage to all non-murloc minions.*/i,
    dealEqualStatsRandomlyEnemies: /.*deal damage equal to this minion's.*randomly.*all enemies.*/i,
    dealRandomEnemy: /.*deal (\d) damage to a random enemy(?:\.|\;).*/i,
    dealEqualStats: /.*deal damage equal to this minion's attack(?:\.|\;).*/i,
    dealAllMinionsExceptDragons: /.*deal (\d) damage to all minions except dragons.*/i,
    dealEqualCostAllMinions: /.*deal damage equal to its cost to all minions*/i,
    dealDragon: /.*deal (\d) damage to a dragon.*/i,
    dealAllOtherMinions: /.*deal (\d) damage to all other minions.*/i,
    dealToIt: /.*deal (\d) damage to it.*/i,
    dealEachHero: /.*deal (\d) damage to each hero.*/i,
    dealInstead: /.*deal (\d) damage instead.*/i,
    dealThatMuchEnemyHero: /.*deal that much damage to the enemy hero.*/i,
    dealThisMinion: /.*deal (\d) damage to this minion.*/i,
    dealThatMuchMinion: /.*deal that much damage to a minion.*/i,
    dealThatMuchAllMinions: /.*deal that much damage to a all minion.*/i,
    dealEqualStatsMinion: /.*deal damage equal to your hero's.*to a minion.*/i,
    dealRandomEnemyMinions: /.*deal (\d) damage to (\d) random enemy minions.*/i,
    dealEnemyCharacter: /.*deal (\d) damage to an enemy character.*/i,
    dealThreeXThree: /.*three missiles at random enemies that deal (\d) damage each*/i,
    dealRandomlyAllEnemies: /.*deal (\d) damage randomly.*all enemies.*/i,
    dealRandomlyAllMinions: /.*deal (\d) damage randomly.*all minions.*/i,
    dealDoubleAllEnemyMinions: /.*deal (\d)-(\d) damage to all enemy minions.*/i,
    dealRandomlyOtherCharacters: /.*deal (\d) damage randomly.*all other characters.*/i,
    dealEqualAttackAllEnemyMinions: /.*deal equal.*attack.*all enemy minions.*/i,
    dealDamagedAllMinion: /.*deal (\d) damage to all damaged minions.*/i,
    dealEqualPlayedCards: /.*deal.*equal to the number of other cards.*this turn.*/i,
    dealRandomlyAllCharacters: /.*deal (\d) damage randomly.*all characters.*/i,
    dealSwipe: /.*deal (\d) damage to an enemy and (\d) damage to all other enemies.*/i,
    dealYourMinions: /.*deal (\d) damage to your minions.*/i,

    // destroy

    destroyOpponentWeapon: /.*destroy.*opponent's weapon.*/i,
    destroyEnemyMinion: /.*destroy an enemy minion.*/i,
    destroyAttackOrMore: /.*destroy a minion with an attack of (\d) or more.*/i,
    destroyAttackOrLess: /.*destroy a minion with (\d) or less.*/i,
    destroyAllAttackOrLess: /.*destroy all minions with (\d) or less attack.*/i,
    destroyAllAttackOrMore: /.*destroy all minions with (\d) or more attack.*/i,
    destroyYourWeapon: /.*destroy.*your weapon.*/i,
    destroyMinion: /.*destroy a minion(?:\.|\;).*/i,
    destroyMinionAndYourManaCrystal: /.*destroy a minion and one of your Mana.*/i,
    destroyEnemyAttackOrLess: /.*destroy an enemy minion with (\d) or less attack.*/i,
    destroyAllMinionsExceptOne: /.*destroy all minions except one.*/i,
    destroyAllMinions: /.*destroy all minions(?:\.|\;).*/i,
    destroyCorrupt: /.*corrupt every minion.*/i,
    destroyIt: /.*destroy it.*/i,
    destroyLeftAndRight: /.*destroy your opponent's left and right.*/i,
    destroyFriendlyMinion: /.*destroy a friendly minion.*/i,
    destroyRandomEnemyMinion: /.*destroy a random enemy minion.*/i,
    destroyallOtherMinions: /.*destroy all other minions.*/i,
    destroyAllEnemySecrets: /.*destroy all enemy secrets.*/i,
    destroyDamagedEnemyMinion: /.*destroy all a damaged enemy minion.*/i,
    destroyYourManaCrystal: /.*destroy one of your mana.*/i,
    destroyPirate: /.*destroy a pirate.*/i,
    destroyMurloc: /.*destroy a murlock?.*/i,
    destroyMurloc: /.*destroy a demon.*/i,
    destroyCardsInYourDeckOrLess: /.*destroy all cards in your deck that cost \((\d)\) or less.*/i,
    destroyFrozenMinion: /.*destroy.*frozen minion.*/i,
    destroyAllDamagedMinions: /.*destroy.*all damaged minions.*/i,
    destroyRandomEnemyMinions: /.*destroy (\d) random enemy minions?.*/i,
    destroyYourHero: /.*destroy your hero.*/i,
    destroyOneCostSpells: /.*destroy all 1-cost spells.*/i,
    destroyRandomEnemyMinionAttackOrLess: /.*destroy a random enemy minion.*with (\d) or less attack.*/i,
    destroyEnemyMinionWithTaunt: /.*destroy an enemy minion with taunt.*/i,
    destroySideMinion: /.*destroy the minions on.*side of this minion.*/i,
    
    // disable hero power

    disableHeroPowers: /.*hero powers are disabled.*/i,

    // discard

    discardHand: /.*discard your hand.*/i,
    discardRandomCard: /.*discard a random card.*/i,
    discardTwo: /.*discard two random cards.*/i,
    discardWeapons: /.*discard all weapons from your hand.*/i,
    discardOthers: /.*discard the others.*/i,

    // enchant

    enchantItDouble: /.*give it \+(\d)\/\+(\d).*/i,
    enchantItAttack: /.*give it \+(\d) attack .*/i,
    enchantAttackTurn: /.*give a minion \+(\d) attack this turn.*/i,
    enchantFriendlyAttack: /.*give a friendly minion \+(\d) attack(?:\.|\;).*/i,
    enchantFriendlyHealth: /.*give a friendly minion \+(\d) health(?:\.|\;).*/i,
    enchantEnemyBananas: /.*give your opponent (\d) bananas.*/i,
    enchantTaunt: /.*give it taunt.*/i,
    enchantItPoisonous: /.*give it poisonous.*/i,
    enchantItToOpponent: /.*give it to your opponent.*/i,
    enchantItDivineShield: /.*give it divine shield.*/i,
    enchantAdjacentSpell: /.*give adjacent minions spell damage \+(\d).*/i,
    enchantAdjacentDoubleTaunt: /.*give adjacent minions \+(\d)\/\+(\d) and taunt.*/i,
    enchantAdjacentDouble: /.*give adjacent minions \+(\d)\/\+(\d)(?:\.|\;).*/i,
    enchantAdjacentHealth: /.*give adjacent minions \+(\d) health.*/i,
    enchantAdjacentTaunt: /.*give adjacent minions taunt.*/i,
    enchantThisAMinionHealth: /.*give (this|a) minion \+(\d) health.*/i,
    enchantEnemyMana: /.*give.*opponent a mana crystal.*/i,
    enchantFriendlyDivineShiled: /.*give a friendly minion divine shield.*/i,
    enchantCthunDouble: /.*give your c'thun \+(\d)\/\+(\d).*/i,
    enchantBeastImmuneAttackturn: /.*give a friendly beast \+(\d) attack and immune this turn.*/i,
    enchantHeroAttackArmorTurn: /.*give your hero \+(\d) attack this turn and (\d) armor.*/i,
    enchantMinionAttack: /.*give a minion \+(\d) attack.*/i,
    enchantMinionWindfury: /.*give a minion windfury.*/i,
    enchantFriendlyMinionWindfury: /.*give a friendly minion windfury.*/i,
    enchantMinionHealth: /.*give a minion \+(\d) health.*/i,
    enchantMinionDouble: /.*give a minion \+(\d)\/\+(\d)(?:\.|\;).*/i,
    enchantRandomFriendlyMinionHealth: /.*give another random friendly minion \+(\d) health.*/i,
    enchantMinionsAttackTurn: /.*give your minions \+(\d) attack this turn.*/i,
    enchantWeaponDouble: /.*give your weapon \+(\d)\/\+(\d).*/i,
    enchantWeaponAttack: /.*give your weapon \+(\d) attack.*/i,
    enchantOtherMinionsHealth: /.*give your other minions \+(\d) health.*/i,
    enchantOtherMinionsDouble: /.*give your other minions \+(\d)\/\+(\d).*/i,
    enchantFriendlyDoubleTaunt: /.*give a friendly minion \+(\d)\/\+(\d) and taunt.*/i,
    enchantFriendlyDouble: /.*give a friendly minion \+(\d)\/\+(\d)(?:\.|\;).*/i,
    enchantMinionsAttack: /.*give your minions \+(\d) attack.*/i,
    enchantMinionsDouble: /.*give your minions \+(\d)\/\+(\d).*/i,
    enchantRandomMinionsDoubleHand: /.*give a random minion in your hand \+(\d)\/\+(\d).*/i,
    enchantMinionsCharge: /.*give a friendly minion charge.*/i,
    enchantRandomFriendlyMinionAttack: /.*give another random friendly minion \+(\d) attack.*/i,
    enchantRandomFriendlyMinionDouble: /.*give another random friendly minion \+(\d)\/\+(\d).*/i,
    enchantYourOtherMurlockHelath: /.*give your other murlocs \+(\d) health.*/i,
    enchantMinionDeathrattle: /.*give a friendly minion.*deathrattle.*/i,
    enchantMinionsDeathrattle: /.*give your minions.*deathrattle.*/i,
    enchantFriendlyImmuneTurn: /.*give a friendly minion immune this turn.*/i,
    enchantWeaponPoisonous: /.*give your weapon poisonous.*/i,
    enchantWeaponLifesteal: /.*give your weapon lifesteal.*/i,
    enchantThemDouble: /.*give them \+(\d)\/\+(\d).*/i,
    enchantHeroAttackTurn: /.*give your hero \+(\d) attack this turn(?:\.|\;).*/i,
    enchantDeathrattleDouble: /.*give all deathrattle minion in your hand \+(\d)\/\+(\d).*/i,
    enchantAllMinionsDouble: /.*give all minions in your hand \+(\d)\/\+(\d).*/i,
    enchantWeaponHandDouble: /.*give a random weapon in your hand \+(\d)\/\+(\d).*/i,
    enchantAdjacentDivineShield: /.*give adjacent minions divine shield.*/i,
    enchantMurlockHandDouble: /.*give a random murloc in your hand \+(\d)\/\+(\d).*/i,
    enchantMinionDivineShield: /.*give a minion divine shield.*/i,
    enchantEnemyCoins: /.*give your opponent two coints.*/i,
    enchantDeckHandWeaponAttack: /.*give all weapons in your hand and deck \+(\d) attack.*/i,
    enchantBeastDoubleTaunt: /.*give a friendly beast \+(\d)\/\+(\d) and taunt.*/i,
    enchantBeastDouble: /.*give a friendly beast \+(\d)\/\+(\d)(?:\.|\;).*/i,
    enchantSilverDoubleHand: /.*give your silver hand.*\+(\d)\/\+(\d) and taunt.*/i,
    enchantMinionDoubleTaunt: /.*give a minion taunt and \+(\d)\/\+(\d).*/i,
    enchantMinionStealth: /.*give a friendly minion stealth.*/i,
    enchantMinionSpellDamage: /.*give a friendly minion spell damage \+(\d).*/i,
    enchantBDM: /.*give a random friendly beast, dragon and murloc \+(\d)\/\+(\d).*/i,
    enchantAllEnemyMinusAttackTurn: /.*give all enemy minions \-(\d) attack.*turn.*/i,
    enchantMinionPoisonous: /.*give a friendly minion poisonous.*/i,
    enchantDoubleWithDivine: /.*give \+(\d)\/\+(\d) to your minions with divine shield.*/i,
    enchantDamagedMinion: /.*give a damaged minion \+(\d)\/\+(\d).*/i,
    enchantCharacterAttackTurn: /.*give a friendly character \+(\d) attack this turn.*/i,
    enchantMurlocDouble: /.*give a friendly murloc \+(\d)\/\+(\d).*/i,
    enchantCharactersAttackTurn: /.*give your characters \+(\d) attack this turn.*/i,
    enchantRandomMinionDivineShield: /.*give a random friendly minion divine shield.*/i,
    enchantStealheadMinion: /.*give a stealhed minion \+(\d)\/\+(\d).*/i,
    enchantRandomBeastDoubleHand: /.*give a random beast.*hand \+(\d)\/\+(\d).*/i,
    enchantMinionDoubleTauntR: /.*give a minion \+(\d)\/\+(\d) and taunt.*/i,
    enchantTauntDoubleHand: /.*give a random taunt minion in your hand \+(\d)\/\+(\d).*/i,
    enchantTauntDouble: /.*give your taunt minions \+(\d)\/\+(\d).*/i,
    enchantRandomFriendlyMinionDoubleN: /.*give a random friendly minion \+(\d)\/\+(\d).*/i,
    enchantTotemsHealth: /.*give your totems \+(\d) health.*/i,
    enchantHandMinionDouble: /.*give a minion in your hand \+(\d)\/\+(\d).*/i,

    // elusive

    elusiveHero: /.*can't be targeted by spells.*/i,
    elusiveMinion: /.*your hero can't be targeted.*/i,

    // equip

    equipDouble: /.*equip a (\d)\/(\d).*/i,
    equipRandom: /.*equip a random weapon.*/i,
    equipAtlesh: /.*equip atlesh.*/i,
    equipReequip: /.*reequip.*/i,

    // forgetful -- empty

    // gain

    gainArmor: /.*gain (\d) armor.*/i,
    gainDoublePlayed: /.*gain \+(\d)\/\+(\d) for each other card.*played.*/i,
    gainDouble: /.*gain \+(\d)\/\+(\d)(?:\.|\;).*/i,
    gainDoubleShield: /.*gain \+(\d)\/\+(\d) for each shield lost.*/i,
    gainAttackEqual: /.*gain attack equal to the attack.*/i,
    gainAttack: /.*gain \+(\d) attack(?:\.|\;).*/i,
    gainAttackTurn: /.*gain \+(\d) attack this turn.*/i,
    gainTaunt: /.*gain.*?taunt.*/i,
    gainCharge: /.*gain.*?charge.*/i,
    gainManaCrystalTurn: /.*gain (\d) mana crystal.*turn.*/i,
    gainManaCrystals: /.*\bgain (\d) mana crystals\.?\;?\b.*/i,
    gainHealth: /.*gain \+(\d) health(?:\.|\;).*/i,
    gainHealthEach: /.*gain \+(\d) health for each enemy minion.*/i,
    gainDoubleEachDamaged: /.*gain \+(\d)\/\+(\d) for each damaged minion.*/i,
    gainArmorEqualToAttack: /.*gain armor equal equal to.*attack.*/i,
    gainDoubleEach: /.*gain \+(\d)\/\+(\d) for each(?:\.|\;).*/i,
    gainDoubleEachTurn: /.*gain \+(\d)\/\+(\d) for each card.*turn.*/i,
    gainControlIt: /.*gain control of it.*/i,
    gainControlAttackLessTurn: /.*gain control of an enemy.*?with (\d) or less attack.*turn.*/i,
    gainDoubleManaSpend: /.*gain \+(\d)\/\+(\d) for each mana spend.*/i,
    gainDoubleMinionsBattle: /.*gain \+(\d)\/\+(\d) for each other friendly minion.*battlefield.*/i,
    gainTheirStats: /.*gain their stats.*/i,
    gainEmptyMana: /.*gain an empty mana crystal(?:\.|\;).*/i,
    gainDoubleTaunt: /.*gain \+(\d)\/\+(\d) and taunt.*/i,
    gainDivine: /.*gain.*?divine shield.*/i,
    gainStealth: /.*gain.*?stealth.*/i,
    gainDeathrattle: /.*gain.*?deathrattle.*/i,
    gainLifesteal: /.*gain.*?lifesteal.*/i,
    gainEachAttackHand: /.*gain \+(\d) attack for each.*card in your hand.*/i,
    gainEachHealthHand: /.*gain \+(\d) health for each.*card in your hand.*/i,
    gainEachHealthElemental: /.*gain \+(\d) health for each.*elemental.*played last turn.*/i,
    gainEqualWeaponDoubke: /.*gain stats equal to your weapon's.*/i,
    gainEmptyManaCrystalsEach: /.*gain an empty mana crystal for each friendly minion.*/i,
    gainBonusHand: /.*gains a bonus effect in your hand.*/i,
    gainTheirDouble: /.*gain their attack and health.*/i,
    gainEachDiedDouble: /.*gain \+(\d)\/\+(\d) for each minion.*?died.*?this turn.*/i,    

    // generate

    addRandomDeathKnight: /.*add a random death knight card.*/i,
    addRandomMageSpell: /.*add a random mage spell.*/i,
    addRandomMageSpells: /.*add (\d) random mage spells?.*/i,
    addRandomDragon: /.*add a random dragon.*/i,
    addDoubleCthun: /.*add its attack and health to c'thun.*/i,
    addCopyEachDamagedFriednlyMinion: /.*add a copy of each damaged friendly minion.*/i,
    addTwoStats: /.*add two (\d)\/(\d).*/i,
    addCoin: /.*add a coin.*/i,
    addWeapon: /.*add a (\d)\/(\d) weapon.*/i,
    addSilvers: /.*add (\d) silver hand.*/i,
    addElemental: /.*add a (\d)\/(\d) elemental.*/i,
    addMirror: /.*add a.*mirror image.*/i,
    addRandomBeast: /.*add a random beast.*/i,
    addRandomPotion: /.*add a random potion.*/i,
    addRandomDemon: /.*add a random demon.*/i,
    addRandomPriestSpell: /.*add a random priest spell.*/i,
    addManaBind: /.*add a copy to your that costs.*/i,
    addCopyOfIt: /.*add a copy of it.*/i,
    addBananas: /.*add (\d) bananas.*/i,
    addRazorpetal: /.*add a razorpetal.*/i,
    addTwoRazorpetals: /.*add two razorpetals.*/i,
    addFirstSeal: /.*add.*?the first seal.*/i,
    addCopyDouble: /.*add (\d)\/(\d) copy.*/i,
    addRandomCard: /.*add a random card.*/i,
    addRandomDeathrattle: /.*add a random deathrattle minion.*/i,
    addFlameGeyser: /.*add.*?flame geyser.*/i,
    addRandomClass: /.*add a random class card.*/i,
    addExtraCopies: /.*add (\d) extra copies.*/i,
    addRandomMinionAttack: /.*add a random minion with (\d) or more attack.*/i,
    addToxin: /.*add a random toxin card.*/i,
    addGoldenCopy: /.*add a golden copy of it.*/i,

    // joust

    revealSpell: /.*reveal a spell.*/i,

    // control effect

    takeControlAttackLess: /.*take control of an enemy minion.*?has (\d) or less attack.*/i,
    takeControlEnemyMinion: /.*take control of an enemy minion(?:\.|\;).*/i,

    // modify cost

    costLessEachSpell: /.*costs \((\d)\) less for each spell.*game.*/i,
    costLessEachDamage: /.*costs \((\d)\) less for each damage.*taken.*/i,
    costLessEachCard: /.*costs \((\d)\) less for each card.*hand.*/i,
    costLessEachMinion: /.*costs \((\d)\) less for each other minion.*battlefield.*/i,
    costLessEachOverload: /.*costs \((\d)\) less for each mana.*overloaded.*/i,
    costWeaponLess: /.*your weapons cost \((\d)\) less.*/i,
    costChangeTo: /.*change its cost to \((\d)\).*/i,
    costReduceEnemyMinion: /.*reduce cost of minions in your opponent's hand by \((\d)\).*/i,
    costItLess: /.*it costs \((\d)\) less.*/i,
    costItMore: /.*it costs \((\d)\) more.*/i,
    costHealth: /.*costs health.*/i,
    costZeroSecret: /.*your secrets cost \((\d)\)(?:\.|\;).*/i,
    costDeathrattleLess: /.*your deathrattle cards cost \((\d)\) less.*/i,
    costSilverControlLess: /.*costs \((\d)\) less for each silver hand.*?control.*/i,
    costEnemySpellMore: /.*your opponent's spells cost \((\d)\) more.*/i,
    costLessPerWeapon: /.*costs \((\d)\) less per attack.*?weapon.*/i,
    costReduceWeapon: /.*reduce.*?random weapon.*?your hand by \((\d)\).*/i,
    costYourMinionsMore: /.*your minions cost \((\d)\) more.*/i,
    costYourMinionsLess: /.*your minions cost \((\d)\) less.*/i,
    costThatLess: /.*that card costs \((\d)\) less.*/i,
    costReduceElementals: /.*reduce.*?elementals.* by \((\d)\).*/i,
    costThey: /.*they cost \((\d)\)(?:\.|\;).*/i,
    costSecretEachLess: /.*costs \((\d)\) less for each secret.*?played this game.*/i,
    costNextSecretLess: /.*next secret.*?this turn.*costs \((\d)\).*/i,
    costLessDrawnMinion: /.*minions drawn cost \((\d)\) less.*/i,
    costAllMinionsMore: /.*all minions cost \((\d)\) more.*/i,
    costFreeEnemyNextTurn: /.*enemy spells cost \((\d)\) next turn.*/i,
    costReduceThis: /.*reduce this card's cost by \((\d)\).*/i,
    costSpellsMore: /.*spells cost \((\d)\) more.*/i,
    costYourSpellsMore: /.*your spells cost \((\d)\) less.*/i,
    costOtherClassLess: /.*cost \((\d)\) less for each card.*?played.*?another class.*/i,
    costFirstMinionLess: /.*first minion.*? costs \((\d)\) less.*/i,
    costSpellLessTurn: /.*next spell.*?this turn.*?costs \((\d)\) less.*/i,
    costReduceItsCost: /.*reduce its cost by \((\d)\).*/i,
    costCardsLess: /.*the cards cost \((\d)\) less.*/i,
    costEachTotemLess: /.*costs \((\d)\) less for each totem.*?game.*/i,

    // multiply attribute

    doubleAttack: /.*double (?:this|a) minion's attack.*/i,
    doubleHealth: /.*double a minion's health.*/i,
    doubleDamageHealing: /.*double the damage adn healing.*/i,
    doubleTwiceTrigger: /.*trigger twice.*/i,
    doubleTwiceAdapt: /.*adapt twice.*/i,

    // no durability loss -- empty 

    // permanent -- empty

    // put 

    putBothPlayersRandomMinion: /.*put a random minion.*?each.*?hand into the battlefield.*/i,
    putMinionDeckToHand: /.*put a 10-cost minion.*?into your hand.*/i,
    putRandomPirateToHand: /.*put a random pirate.*?into your hand.*/i,
    putAllDragonFromHand: /.*put all dragons.*into the battlefield.*/i,
    putEachSecretBattlefield: /.*put one of each secret.*?into the battlefield.*/i,
    putCopySpellPlayers: /.*put a copy into the other player's hand.*/i,
    putCopyOpponentCard: /.*put a copy of a random card.*opponent's hand.*/i,
    putCopyOpponentMinion: /.*put a copy of a random minion.*?opponent's deck.*?into the battlefield.*/i,
    putRandomHunterSecretBattlefield: /.*put a random hunter secret.*?into the battlefield.*/i,
    putRandomDemonsToHand: /.*put (\d) random demons.*?from your deck into your hand.*/i,
    putMinionDeckToBattlefield: /.*put a minion from your deck into the battlefield.*/i,

    // refresh

    refreshHeroPower: /.*refresh your hero power.*/i,
    refreshMana: /.*refresh your mana crystals.*/i,

    // remove from deck
    // replace
    // restore health
    // return
    // set attribute
    // shuffle into deck
    // spend mana
    // summon
    // transform
    // transform in hand
    // unlimited attacks


}