export const cardTextMechanicsRegex = {
    // dealsDamage: /.*\bdeals damage\b.*/i,
    // dealItsDamage: /.*\bdeal its damage\b.*/i,
    // dealThatMuchDamage: /.*\bdeal that much damage\b.*/i,
    // dealRandom: /.*\bdeal random\b.*/i,

    cardDraw: /.*\bdraw\b.*/i,
    castSpell: /.*\bcast\b.*/i,
    copy: /.*\bcopy\b.*/i,
    dealDamage: /.*deals? \$?(\d*) (?:extra|damage).*/i,
    destroy: /.*\bdestroy\b.*/i,
    disableHeroPower: /.*\bdisabled?\b.*/i,
    discard: /.*\bdiscard\b.*/i,
    enchant: /.*\benchant\b.*/i,
    elusive: /.*\bbe targeted\b.*/i,
    equip: /.*\bequip\b.*/i,
    forgetful: /.*\bwrong\b.*/i,
    gainArmor: /.*\bgain \d? armor\b.*/i,
    generate: /.*\bgenerate\b.*/i,
    incrementAttribute: /.*\bgive\b.*/i,
    joust: /.*\breveals?\b.*/i,
    mindControlEffect: /.*\bcontrol\b.*/i,
    modifyCost: /.*\bgive\b.*/i,
    multiplyAttribute: /.*\bdouble\b.*/i,
    noDurabilityLoss: /.*\bgive\b.*/i,
    permanent: /.*\bpermanent\b.*/i,
    putIntoBattlefield: /.*\bgive\b.*/i,
    putIntoHand: /.*\bgive\b.*/i,
    refreshMana: /.*\brefresh\b.*/i,
    removeFromDeck: /.*\bremove\b.*/i,
    replace: /.*\breplace\b.*/i,
    restoreHealth: /.*\brestore\b.*/i,
    return: /.*\breturn\b.*/i,
    setAttribute: /.*\bset\b.*/i,
    shuffleIntoDeck: /.*\bshuffle\b.*/i,
    spendMana: /.*\bspends?\b.*/i,
    summon: /.*\bsummons?\b.*/i,
    transform: /.*\btransorms?\b.*/i,
    transformInHand: /.*\bgive\b.*/i,
    unlimitedAttacks: /.*\bunlimited\b.*/i
}