export const targetRegex = {
    allMinions: /.*all minions.*/i,
    allOtherEnemies: /.*all other enemies.*/i,
    allOtherMinions: /.*all other minions.*/i,
    allEnemyMinions: /.*all enemy minions.*/i,
    yourMinions: /.*your minions.*/i,
    minion: /.*(?:a minion|a\\nminion).*/i,
    randomMinion: /.*a random minion.*/i,
    yourHeroPower: /.*your hero power.*/i,
    randomMinions: /.*random minions.*/i,
    allEnemies: /.*all enemies.*/i,
    allOtherCharacters: /.*all other characters.*/i,
    adjacentOnes: /.*adjacent ones.*/i,
    enemyMinions: /.*enemy minions.*/i,
    enemyMinion: /.*an enemy minion.*/i,
    undamagedCharacter: /.*undamaged character.*/i,
    damagedMinions: /.*damaged minions.*/i,
    it: /.* to it.*/i,
    eachHero: /.*each hero.*/i,
    thisMinion: /.*this minion.*/i,
    allCharacters: /.*all characters.*/i,
    randomEnemy: /.*a random enemy.*/i,
    randomEnemyMinions: /.*random enemy minions.*/i,
    randomEnemies: /.*at random enemies.*/i,
    himself: /.*himself.*/i,
    amongEnemyCharacters: /.*among enemy characters.*/i,
    undamagedMinion: /.*undamaged minion.*/i,
    randomEnemyMinion: /.*a random enemy minion.*/i,
    nonMurclockMinions: /.*non-murloc minions.*/i,
    exceptDragons: /.*except dragons.*/i,

    yourOtherMinions: /.*your other minions.*/i,
    yourWeapons: /.*your weapons.*/i,
    youHave: /.*you have.*/i,
    theyHave: /.*they have.*/i,
    bothPlayers: /.*both players.*/i,
    yourDeck: /.*your deck.*/i,
    yourOpponent: /.*your opponent.*/i,
    eachPlayer: /.*each player.*/i,
    forEach: /.*for each.*/i,
    yourMinion: /.*\byour minion\b.*/i,
    yourHand: /.*\byour hand\b.*/i,
    otherPlayersHand: /.*\bother player's hand\b.*/i,
    yourHero: /.*your hero.(?!power).*/i,
    randomSpell: /.*a random spell.*/i,
    randomWeapon: /.*a random weapon.*/i,
    randomCard: /.*\brandom card\b.*/i,
    frozenMinion: /.*frozen minion.*/i,
    opponentsWeapon: /.*your opponent's weapon.*/i,
    minionNumberPlus: /.*a minion with an attack of (\d\d?) or more.*/i,
    yourWeapon: /.*\byour weapon\b.*/i,
    manaCrystals: /.*your mana crystals.*/i,
    enemmyMinionNumberLess: /.*an enemy minion with (\d\d?) or less attack.*/i,
    minionNumerLess: /.*a minion with (\d\d?) or less attack.*/i,
    allMinionsExceptOne: /.*all minions except one.*/i,
    friendlyMinion: /.*a friendly minion.*/i,
    them: /.*them.*/i,
    opponentLRM: /.*your opponent's left and right-most minions.*/i,
    pirate: /.*\bpirate\b.*/i,
    murloc: /.*\bmurloc\b.*/i,
    murlocs: /.*\bmurlocs\b.*/i,
    demon: /.*\bdemon\b.*/i,
    allCards: /.*all cards.*/i,
    allDamagedMinion: /.*all damaged minions.*/,
    allMinionsNumberLess: /.*all minions with (\d\d?) or less attack.*/i,
    allOneCostSpells: /.*all 1-cost spells in both hands and decks.*/i,
    randomEnemyMinionNumerLess: /.*a random enemy minion with (\d\d?) or less attack.*/i,
    minionSide: /.*the minions on either side of this minion.*/i,
    heroPowers: /.*\bhero powers\b.*/i,
    dreamCard: /.*a dream card.*/i,
    twoOneCost: /.*two 1-cost minions.*/i,
    threeOneCost: /.*three 1-cost minions.*/i,
    BDM: /.*a beast, dragon and murlock.*/i,
    divineShieldMinion: /.*a divine shield minion.*/i,
    weapon: /.*\bweapon\b.*/,
    weapons: /.*\bweapons\b.*/,
    secret: /.*\bsecret\b.*/,
    card: /.*\bcard\b.*/,
    twoRandomCards: /.*two random cards.*/i,
    wrongEnemy: /.*wrong enemy.*/i,
    enemyHero: /.*enemy_?hero.*/i,
    randomToxinCard: /.*random toxin card.*/i

};