export const targetRegex = {
    allMinions: /.* all minions.*/i,
    allOtherEnemies: /.* all other enemies.*/i,
    allOtherMinions: /.* all other minions.*/i,
    allEnemyMinions: /.* all enemy minions.*/i,
    yourMinions: /.* your minions.*/i,
    minion: /.* a minion.*/i,
    randomMinion: /.* a random minion.*/i,
    yourHero: /.* your hero.*/i,
    randomMinions: /.* random minions.*/i,
    allEnemies: /.* all enemies.*/i,
    allOtherCharacters: /.* all other characters.*/i,
    adjacentOnes: /.* adjacent ones.*/i,
    enemyMinions: /.* enemy minions.*/i,
    enemyMinion: /.* an enemy minion.*/i,
    undamagedCharacter: /.* undamaged character.*/i,
    damagedMinions: /.* damaged minions.*/i,
    it: /.* to it.*/i,
    eachHero: /.* each hero.*/i,
    thisMinion: /.* this minion.*/i,
    allCharacters: /.* all characters.*/i,
    randomEnemy: /.* a random enemy.*/i,
    randomEnemyMinions: /.* random enemy minions.*/i,
    randomEnemies: /.*at random enemies.*/i,
    himself: /.* himself.*/i,
    amongEnemyCharacters: /.* among enemy characters.*/i,
    undamagedMinion: /.* undamaged minion.*/i,
    randomEnemyMinion: /.* a random enemy minion.*/i,
    nonMurclockMinions: /.* non-murloc minions.*/i,
    exceptDragons: /.* except dragons.*/i,

    yourOtherMinions: /.* your other minions.*/i,
    yourWeapons: /.* your weapons.*/i,
};